/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/admin/entidades/': RouteRecordInfo<'/admin/entidades/', '/admin/entidades', Record<never, never>, Record<never, never>>,
    '/admin/entidades/[id]': RouteRecordInfo<'/admin/entidades/[id]', '/admin/entidades/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/tags': RouteRecordInfo<'/admin/tags', '/admin/tags', Record<never, never>, Record<never, never>>,
    '/entidades/[id]': RouteRecordInfo<'/entidades/[id]', '/entidades/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
