/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/entities/': RouteRecordInfo<'/admin/entities/', '/admin/entities', Record<never, never>, Record<never, never>>,
    '/admin/entities/[id]': RouteRecordInfo<'/admin/entities/[id]', '/admin/entities/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/tags': RouteRecordInfo<'/admin/tags', '/admin/tags', Record<never, never>, Record<never, never>>,
    '/entities/[id]': RouteRecordInfo<'/entities/[id]', '/entities/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
