create type entity_type as enum (
	'pais',
	'estado',
	'municipio',
	'distrito_federal',
	'distrito_estadual',
	'regiao_administrativa',
	'vila'
);

create table entities (
	id integer generated by default as identity primary key,
	name text not null,
	image text,
	type entity_type not null,
	uf char(2)
);

create table tags (
	id integer generated by default as identity primary key,
	name text not null,
	parent_id integer references tags
);

create table entity_tags (
	id bigint generated always as identity primary key,
	entity_id integer not null references entities,
	tag_id integer not null references tags,
	unique(entity_id, tag_id)
);
